### ISSUE TITLE
Plot orbits just crashed

### ISSUE THREAD

**Issue by weka511** [weka511/galaxy#5]
Data generated by  ./galaxy -e 100 -i 100 -n 2000 -f 0.001 and plot_orbits run with defaults.
Traceback (most recent call last):
  File "plot_orbits.py", line 106, in <module>
    data=extract(selector=selector,maxsamples=args.maxsamples,prefix=args.prefix,suffix=args.suffix,delimiter=args.delimiter)
  File "plot_orbits.py", line 82, in extract
    result.append([positions[i] for i in selector])
  File "plot_orbits.py", line 82, in <listcomp>
    result.append([positions[i] for i in selector])
IndexError: index 143 is out of bounds for axis 0 with size 100

**Comment by weka511** [comment]
Problem caused by using ./galaxy.exe to generate a small number of bodies, followed by a large number. Need to purge configs at the start of a run.
